# Simple workflow for deploying static content to GitHub Pages
name: Deploy Static Website to GitHub Pages

on:
  # 'main' dalına (branch) her kod gönderildiğinde (push) otomatik çalışır
  push:
    branches: ["main"]

  # GitHub üzerinden manuel olarak tetiklemeye izin verir
  workflow_dispatch:

# Gerekli izinleri ayarlıyoruz
permissions:
  contents: read
  pages: write
  id-token: write

# Aynı anda tek bir yayınlama yapılmasını sağlar
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Kök dizindeki HTML/CSS/JS dosyalarını paketler
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
